server.port=8080
spring.application.name=polizas-service

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://mysql-service:3306/db_polizas
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Feign Clients Configuration (Internal URLs)
clients.service.url=http://clients-service:8081
plans.service.url=http://plans-service:8082
